[package]
name = "rustphantompurger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = "0.17"
clap = { version = "4", features = ["derive"] }
statrs = "0.16"
itertools="0.11"
bustools = { path = "/home/michi/Dropbox/rustbustools", version="0.9"  }
flate2 = "1"
